server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # --- INICIO CONFIGURACIÓN CORS ---
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173" # Damos permiso explícito a tu frontend de React
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS # Vital para que el preflight no de error 403
            allowedHeaders: "*"
            allowCredentials: true
      # --- FIN CONFIGURACIÓN CORS ---
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
instance:
    prefer-ip-address: true

jwt:
  secret: "smartlogix-super-secret-key-1234567890"

management:
  endpoints:
    web:
      exposure:
        include: '*'