server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
    discovery:
      enabled: true
      service-id: eureka-server
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
