server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smartlogix_users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      enabled: true
      service-id: eureka-server
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
